<head>
    <script type="text/javascript">

        function pridajAutora() {
            var radku = document.getElementById('autor').rows.length;
            var radek = document.getElementById('autor').insertRow(radku);
            var bunka1 = radek.insertCell(0);
            var bunka2 = radek.insertCell(1);
            var bunka3 = radek.insertCell(2);
            var bunka4 = radek.insertCell(3);
            var bunka5 = radek.insertCell(4);
            var bunka6 = radek.insertCell(5);
            bunka1.innerHTML = "<tr> <td> <input class=formular_vstup type=text placeholder=titul name=titul_pred_" + (radku - 1) + " > ";
            bunka2.innerHTML = "<td><input class=formular_vstup  type=text placeholder=meno name=meno_" + (radku - 1) + " > ";
            bunka3.innerHTML = "<td> <input class=formular_vstup type=text  placeholder=priezvisko name=priezvisko_" + (radku - 1) + " > ";
            bunka4.innerHTML = "<td> <input class = formular_vstup type=text placeholder=titul name=titul_po_" + (radku - 1) + " > ";
            bunka5.innerHTML = "  <input type=button onclick=pridajAutora() value=+ />      ";
            bunka6.innerHTML = "  <input type=button onclick=odstranAutora(this) value=x />  ";
            return false;
        }

        function odstranAutora(r) {
            var i = r.parentNode.parentNode.rowIndex;
            document.getElementById("autor").deleteRow(i);
        }

        function pridajOkruh() {
            var radku = document.getElementById('okruhy').rows.length;
            var radek = document.getElementById('okruhy').insertRow(radku);
            var bunka = radek.insertCell(0);
            var bunka1 = radek.insertCell(1);
            var bunka2 = radek.insertCell(2);
            bunka.innerHTML = " <input class=formular_vstup type=text  name=nazov_okruhu_" + (radku - 1) + "  >  ";
            bunka1.innerHTML = "  <input type=button onclick=pridajOkruh() value=+ />      ";
            bunka2.innerHTML = "  <input type=button onclick=odstranOkruh(this) value=x>  ";
            return false;
        }

        function odstranOkruh(r) {
            var i = r.parentNode.parentNode.rowIndex;
            document.getElementById("okruhy").deleteRow(i);
        }

        function pridajSlovo() {
            var radku = document.getElementById('slova').rows.length;
            var radek = document.getElementById('slova').insertRow(radku);
            var bunka = radek.insertCell(0);
            var bunka1 = radek.insertCell(1);
            var bunka2 = radek.insertCell(2);
            bunka.innerHTML = " <input class=formular_vstup type=text name=klucove_slovo_" + (radku - 1) + "  >  ";
            bunka1.innerHTML = "  <input type=button onclick=pridajSlovo() value=+ />      ";
            bunka2.innerHTML = "  <input type=button onclick=odstranSlovo(this) value=x>  ";
            return false;
        }


        function odstranSlovo(r) {
            var i = r.parentNode.parentNode.rowIndex;
            document.getElementById("slova").deleteRow(i);
        }
    </script>
</head>


<div id="administracia" >
    <img src="resources/ikony/user.png"> <?php echo $pouzivatel['meno'] ?> 
    <a  class= "tucny_odkaz" href="uvod/odhlasit"> <img src="resources/ikony/exit.png"> </a>
</div>


<div id="navigacia">
    <a class="tucny_odkaz" href="uvod"> DATALEO </a> >>
    <a class="tucny_odkaz" href="zdroje"> Moja knižnica </a> >> Pridanie nového zdroja
</div>



<div id="editor" >

    <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="zdroj_id" value="<?= $zdroj['zdroj_id'] ?>"/>
        <input type="hidden" name="id" value="<?= $autor_zdroj['id'] ?>"/>

        <!-- tu bolo pridane _0, moze to sposobit chybu? -->
        <input type="hidden" name="autor_id" value="<?= $autor['autor_id_0'] ?>"/>
        <input type="hidden" name="klucove_slovo_id" value="<?= $klucove_slovo['klucove_slovo_id_0'] ?>"/>
        <input type="hidden" name="okruh_id" value="<?= $okruh['okruh_id_0'] ?>"/>

        <input type="hidden" name="pouzivatel_id" value="<?= $zdroj['pouzivatel_id'] ?>"/>
        <input type="hidden" name="datum_pridania" value="<?= $zdroj['datum_pridania'] ?>"/>



        <table  id= "autor" class="autor" border="0"  >
            <th colspan = "10" class="autor">  Autor:  </th>
            <?php if (((isset($autor[0]['titul_pred'])) OR ( isset($autor[0]['meno'])) OR ( isset($autor[0]['priezvisko'])) OR ( isset($autor[0]['titul_po']))) == true): ?> 
                <?php if (isset($autor[0]['titul_pred'])): ?>
                    <tr><td><input class="formular_vstup"  type="text" placeholder="titul" name="titul_pred_0" value="<?= $autor[0]['titul_pred'] ?>" autofocus/> </td>
                    <?php endif; ?>

                    <?php if (isset($autor[0]['meno'])): ?>
                        <td><input class="formular_vstup"  type="text" placeholder="meno" name="meno_0" value="<?= $autor[0]['meno'] ?>" /> </td>
                    <?php endif; ?>
                    <?php if (isset($autor[0]['priezvisko'])): ?>
                        <td><input class="formular_vstup" type="text"  placeholder="priezvisko" name="priezvisko_0" value="<?= $autor[0]['priezvisko'] ?>"/> </td>
                    <?php endif; ?>
                    <?php if (isset($autor[0]['titul_po'])): ?>
                        <td><input class="formular_vstup" type="text"  placeholder="titul" name="titul_po_0" value="<?= $autor[0]['titul_po'] ?>" /> </td>
                    <?php endif; ?>

                <?php else: ?>
                <tr><td><input class="formular_vstup"  type="text" placeholder="titul" name="titul_pred_0" /> </td>
                    <td><input class="formular_vstup" type="text"  placeholder="meno" name="meno_0"  /> </td>
                    <td><input class="formular_vstup" type="text"  placeholder="priezvisko" name="priezvisko_0" /> </td>
                    <td><input class="formular_vstup" type="text"  placeholder="titul" name="titul_po_0" /> </td>
                <?php endif; ?>    

                <td> <input type="button" onclick="pridajAutora()" value="+"  />    </td>           

                <?php
                for ($a = 1; $a <= 100; $a++) {
                    if (isset($autor[$a])) { // tu moze byt zrada,autor ma viac poloziek
                        ?>

                        <?php if (isset($autor[$a]['titul_pred'])): ?>
                        <tr><td> <input type="text" class="formular_vstup"   name="titul_pred_<?= $a ?>"  value="<?= $autor[$a]['titul_pred'] ?>" /></td>
                        <?php endif; ?> 

                        <?php if (isset($autor[$a]['meno'])): ?>
                            <td> <input type="text" class="formular_vstup"   name="meno_<?= $a ?>"  value="<?= $autor[$a]['meno'] ?>" /></td>
                        <?php endif; ?> 

                        <?php if (isset($autor[$a]['priezvisko'])): ?>
                            <td> <input type="text" class="formular_vstup"    name="priezvisko_<?= $a ?>"  value="<?= $autor[$a]['priezvisko'] ?>" /></td>
                        <?php endif; ?> 

                        <?php if (isset($autor[$a]['titul_po'])): ?>
                            <td> <input type="text" class="formular_vstup"   name="titul_po_<?= $a ?>"  value="<?= $autor[$a]['titul_po'] ?>" /></td>
                        <?php endif; ?> 

                        <td> <input type="button" onclick="pridajAutora()" value="+" />    </td>
                        <td><input type=button onclick="odstranAutora(this)" value=x> </td>

                        <?php
                    };
                };
                ?>
        </table>


        <table  class="info_zdroj" border="0">
            <th colspan=10 class="info_zdroj"> Informácie o zdroji: </th>

            <tr> <td> Názov:</td>
                <td colspan="7"><input class="formular_vstup" type="text" name="nazov" value="<?= $zdroj['nazov'] ?> "/> </td></tr>

            <tr><td> Podnázov:</td>
                <td colspan="7"> <input class="formular_vstup" type="text" name="podnazov" value="<?= $zdroj['podnazov'] ?>"/> </td></tr>

            <tr> <td> Vydanie:</td>
                <td><input class="formular_vstup" type="text" name="vydanie" value="<?= $zdroj['vydanie'] ?>"/> </td> 

                <td> Miesto vydania:</td>
                <td><input class="formular_vstup" type="text" name="miesto_vydania" value="<?= $zdroj['miesto_vydania'] ?>" /> </td>

                <td> Vydavateľstvo:</td>
                <td><input class="formular_vstup" type="text" name="vydavatelstvo" value="<?= $zdroj['vydavatelstvo'] ?>"/> </td>

                <td> Rok vydania: </td>
                <td><input class="formular_vstup" type="text" name="rok_vydania" value="<?= $zdroj['rok_vydania'] ?>"/> </td></tr> 

            <tr> <td> ISBN:</td>
                <td><input class="formular_vstup" type="text" name="isbn" value="<?= $zdroj['isbn'] ?>"/> </td>

                <td> ISSN:</td>
                <td><input class="formular_vstup" type="text" name="issn" value="<?= $zdroj['issn'] ?>"/> </td>

                <td> DOI: </td>
                <td><input class="formular_vstup" type="text" name="doi" value="<?= $zdroj['doi'] ?>"/> </td></tr>

            <tr> <td> Počet strán:</td>
                <td><input class="formular_vstup" type="text" name="strany" value="<?= $zdroj['strany'] ?>"/> </td>

                <td> URL adresa:</td>
                <td><input class="formular_vstup" type="text" name="url" value="<?= $zdroj['url'] ?>"/> </td> 

                <td> Dátum aktualizácie:</td> 
                <td><input class="formular_vstup" type="text" name="datum_aktualizacie" value="<?= $zdroj['datum_aktualizacie'] ?>"/> </td></tr> 

            <tr> <td> Hodnotenie:</td>
                <td> <select name="hodnotenie" class="formular_vstup">
                        <?php if (($zdroj['hodnotenie']) == 1): ?>
                            <option value="1" selected> 1 - výborné </option>
                            <option value="2" > 2 - veľmi dobré </option>
                            <option value="3" > 3 - dobré </option>
                            <option value="4" >4 - uspokojivé </option>
                            <option value="5" > 5 - zlé </option>

                        <?php elseif (($zdroj['hodnotenie']) == 2): ?>
                            <option value="2" selected> 2 - veľmi dobré </option>
                            <option value="1" > 1 - výborné </option>
                            <option value="3" > 3 - dobré </option>
                            <option value="4" >4 - uspokojivé </option>
                            <option value="5" > 5 - zlé </option>

                        <?php elseif (($zdroj['hodnotenie']) == 3): ?>
                            <option value="3" selected> 3 - dobré </option>
                            <option value="1" > 1 - výborné </option>
                            <option value="2" > 2 - veľmi dobré </option>
                            <option value="4" >4 - uspokojivé </option>
                            <option value="5" > 5 - zlé </option>

                        <?php elseif (($zdroj['hodnotenie']) == 4): ?>
                            <option value="4" selected>4 - uspokojivé </option>
                            <option value="1" > 1 - výborné </option>
                            <option value="2" > 2 - veľmi dobré </option>
                            <option value="3" > 3 - dobré </option>
                            <option value="5" > 5 - zlé </option>

                        <?php elseif (($zdroj['hodnotenie']) == 5): ?>
                            <option value="1" > 1 - výborné </option>
                            <option value="2" > 2 - veľmi dobré </option>
                            <option value="3" > 3 - dobré </option>
                            <option value="4" >4 - uspokojivé </option>
                            <option value="5" selected> 5 - zlé </option>

                        <?php else: ?>
                            <option value="1" > 1 - výborné </option>
                            <option value="2" > 2 - veľmi dobré </option>
                            <option value="3" > 3 - dobré </option>
                            <option value="4" >4 - uspokojivé </option>
                            <option value="5" > 5 - zlé </option>
                        <?php endif ?>
                    </select>
                </td>

                <td> Poznámka:</td>
                <td colspan="5"><textarea class="formular_vstup" name="poznamka"><?= $zdroj['poznamka'] ?></textarea> </td></tr> 

            <tr><td> Pridať PDF: </td>
                <td> <input  type="file" name="file">  </td> </tr>



        </table> 



        <table id="druhy" class="druhy" border="0">
            <th class="druhy"> Druh zdroja:</th>
            <tr><td> <select name="druh_zdroja" class="formular_vstup" >

                        <?php if (($zdroj['druh_zdroja']) == "kniha"): ?>
                            <option value="kniha" selected> Kniha </option>
                            <option value="cast_knihy" > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "cast_knihy"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy" selected > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "periodikum"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" selected> Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "clanok"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum"  > Periodikum </option>
                            <option value="clanok" selected> Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "zbornik"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" selected> Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "prispevok_v_zborniku"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" selected> Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>



                        <?php elseif (($zdroj['druh_zdroja']) == "akademicka_praca"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" selected> Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "elektronicka_kniha"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" selected> Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "cast_elektronickej_knihy"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" selected> Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "elektronicke_periodikum"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" selected> Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>


                        <?php elseif (($zdroj['druh_zdroja']) == "elektronicky_clanok"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" selected> Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "elektronicky_zbornik"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" selected> Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "elektronicka_akademicka_praca"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" selected> Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "elektronicky_prispevok_v_zborniku"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" selected> Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>



                        <?php elseif (($zdroj['druh_zdroja']) == "web"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" selected> Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "webova_stranka"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" selected> Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "prispevok_na_webe"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" selected> Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "iny_dokument"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" selected> Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>

                        <?php elseif (($zdroj['druh_zdroja']) == "nepublikovany_dokument"): ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="prispevok_na_webe" > Príspevok na webe </option>
                            <option value="iny_dokument" > Iný dokument </option>
                            <option value="nepublikovany_dokument" selected> Nepublikovaný dokument </option>



                        <?php else: ?>
                            <option value="kniha" > Kniha </option>
                            <option value="cast_knihy"  > Časť knihy </option>
                            <option value="periodikum" > Periodikum </option>
                            <option value="clanok" > Článok </option>
                            <option value="zbornik" > Zborník </option>
                            <option value="prispevok_v_zborniku" > Príspevok v zborníku </option>
                            <option value="akademicka_praca" > Akademická práca </option>
                            <option value="elektronicka_kniha" > Elektronická kniha </option>
                            <option value="cast_elektronickej_knihy" > Časť elektronickej knihy </option>
                            <option value="elektronicke_periodikum" > Elektronické periodikum </option>
                            <option value="elektronicky_clanok" > Elektronický článok</option>
                            <option value="elektronicky_zbornik" > Elektronický zborník </option>
                            <option value="elektronicka_akademicka_praca" > Elektronická akademická práca </option>
                            <option value="elektronicky_prispevok_v_zborniku" > Elektronický príspevok v zborníku </option>
                            <option value="web" > Web </option>
                            <option value="webova_stranka" > Webová stránka </option>
                            <option value="iny_dokument" selected> Iný dokument </option>
                            <option value="nepublikovany_dokument" > Nepublikovaný dokument </option>
                        <?php endif ?>
                    </select>
                </td></tr> 
        </table>

        <table class="okruhy" id="okruhy" border="0" >
            <th class="okruhy" colspan=3> Okruhy: </th>

            <?php if (isset($okruh[0]['nazov_okruhu'])): ?>
                <tr><td><input class="formular_vstup" type="text"  name="nazov_okruhu_0" value="<?= $okruh[0]['nazov_okruhu'] ?>"/></td>
                <?php else: ?>
                <tr><td><input class="formular_vstup" type="text"  name="nazov_okruhu_0" /></td>
                <?php endif; ?>
                <td> <input type="button" onclick="pridajOkruh()" value="+" />    </td>
                <?php
                for ($j = 1; $j <= 100; $j++) {
                    if (isset($okruh[$j])) {
                        ?>
                    <tr><td> <input type="text" class="formular_vstup"  name="nazov_okruhu_<?= $j ?>"  value="<?= $okruh[$j]['nazov_okruhu'] ?>" /></td>
                        <td> <input type="button" onclick="pridajOkruh()" value="+" />    </td>
                        <td><input type=button onclick=odstranOkruh(this) value=x> </td>

                        <?php
                    };
                };
                ?>
        </table>



        <table id="slova" class="slova" border="0" >
            <th class="slova" colspan="3"> Kľúčové slová: </th>

            <?php if (isset($klucove_slovo[0]['klucove_slovo'])): ?>
                <tr><td><input class="formular_vstup" type="text"  name="klucove_slovo_0" value="<?= $klucove_slovo[0]['klucove_slovo'] ?>"/></td>
                <?php else: ?>
                <tr><td><input class="formular_vstup" type="text"  name="klucove_slovo_0" /></td>
                <?php endif; ?>
                <td> <input type="button" onclick="pridajSlovo()" value="+" />    </td>
                <?php
                for ($i = 1; $i <= 10; $i++) {
                    if (isset($klucove_slovo[$i])) {
                        ?>
                    <tr><td> <input type="text" class="formular_vstup"    name="klucove_slovo_<?= $i ?>"  value="<?= $klucove_slovo[$i]['klucove_slovo'] ?>" /></td>
                        <td> <input type="button" onclick="pridajSlovo()" value="+" />    </td>
                        <td><input type=button onclick=odstranSlovo(this) value=x> </td>

                        <?php
                    };
                };
                ?>
        </table>

        <table class="pridanie_zdroja_tlacidla">
            <tr> <td><input class= "potvrdzovacie_tlacidlo" type="submit" value="Pridať zdroj" /></td>



            <tr>  <td align="right"><input class= "tucny_odkaz"  type="reset" value="Vymazať formulár"></td>
            </tr>

        </table> 
    </form>
</div>