<div id="administracia" >
    <img src="user.png"> <?php echo $pouzivatel['meno'] ?> 
    <a  class= "modry_odkaz" href="uvod/odhlasit"> <img src="exit.png"> </a>

</div>


<div id="navigacia">
    <a class="modry_odkaz" href="uvod"> DATALEO </a>  >> Moja knižnica
</div>

<div id="chyba">
    <h3>   Vitajte! Zatiaľ nemáte pridaný žiaden záznam. </h3>
    <a class="potvrdzovacie_tlacidlo" href="editor"> Pridať nový záznam. </a>
        
</div>