
<div id="prihlasenie">
<h1> Prihlásenie </h1>
    <form method="post">
        <table border="0" align="center" >
            <tr> <td> Login: <td><input class="formular_vstup" type="text" name="login" /></td></tr>
            <tr> <td> Heslo:  <td><input class="formular_vstup" type="password" name="heslo" /> </td></tr>
        </table>
        <input class="potvrdzovacie_tlacidlo" type="submit" value="Prihlásiť" /> <br>
        <p > Nie ste zaregistrovaní? <a  class="tucny_odkaz" href="registracia"> Registrácia </a></p>

    </form> 
</div>




