<div id='registracia'>
   <form method="post">
    <br> <b>Prihlásenie</b> <br> <br>
    <table border="0" align="center" >
        <tr> <td> Login: <td><input type="text" name="login" /></td></tr>
        <tr> <td> Heslo:  <td><input type="password" name="heslo" /> </td></tr>
    </table>
    <input type="submit" value="Prihlásiť" /> <br>
    
    <br> Ak ešte nemáte účet, <a href="http://localhost/registracia"> zaregistrujte sa</a>.
    <br> <a href='http://localhost'> Späť na úvod. </a>

</form> 
</div>




