
<div id="registracia">
    <h1> Registrácia </h1>
    <form method="post">
        <table border="0" align="center" >
            <tr> <td> Meno: <td><input class="formular_vstup" type="text" name="meno_reg" /></td></tr>
            <tr> <td> Heslo:  <td><input class="formular_vstup" type="password" name="heslo_reg" /> </td></tr>
            <tr> <td> Heslo znovu: <td> <input class="formular_vstup" type="password" name="heslo_znovu_reg" /> </td></tr>
            <tr> <td> E-mail:  <td><input class="formular_vstup" type="text" name="email" /> </td></tr>
        </table>
        <p class="sive_pismo"> * Súhlasím so spracovaním mojich údajov.</p>
        <br> <input class="potvrdzovacie_tlacidlo" type="submit" value="Zaregistrovať" /><br>
    </form>
</div>