
<div id="registracia">
    <h1> Registrácia </h1>
    <form method="post">
        <table border="0" align="center" >
            <tr> <td> Meno: <td><input class="formular_vstup" type="text"  required name="meno_reg" /></td></tr>
            <tr> <td> Heslo:  <td><input class="formular_vstup" type="password" required name="heslo_reg" /> </td></tr>
            <tr> <td> Heslo znovu: <td> <input class="formular_vstup" type="password"  required name="heslo_znovu_reg" /> </td></tr>
            <tr> <td> E-mail:  <td><input class="formular_vstup" type="email" required name="email" /> </td></tr>
        </table>
        <input type="hidden" name="zaskrtavatko" value="0" > <!-- je potrebne skryty formular a nastavena defaultna hodnota lebo pisalo undefined index zaskrtavatko stale ked to pri registracii nebolo zaskrtnute  -->
        <input  type="checkbox" name="zaskrtavatko" value="ano" >  Súhlasím so spracovaním mojich údajov.
        <br> <input class="potvrdzovacie_tlacidlo" type="submit" value="Zaregistrovať" /><br>
    </form>
</div>