<div id="registracia">


    <form method="post">
        <br> <b>Registrácia nového člena</b> <br> <br>
        <table border="0" align="center" >
            <tr> <td> Meno: <td><input type="text" name="meno_reg" /></td></tr>
            <tr> <td> Heslo:  <td><input type="password" name="heslo_reg" /> </td></tr>
            <tr> <td> Heslo znovu: <td> <input type="password" name="heslo_znovu_reg" /> </td></tr>
            <tr> <td> E-mail:  <td><input type="text" name="email" /> </td></tr>
        </table>
        
    
     <br> <input type="submit" value="Zaregistrovať" />
     <br> <br>*Zaregistrovaním sa súhlasíte s podmienkami používania systému Dataleo a so spracovaním osobných údajov pre potreby aplikácie.
    
    </form>
</div>