<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost"/>
        <meta charset="UTF-8"/>
        <title><?= $titulok ?> </title>
        <meta name="description" content="<?= $popis ?>"/>
        <meta name="keywords" content="<?= $klucove_slova ?>"/>
        <link rel="stylesheet" href="style.css" type="text/css"/>     
        <link rel="shortcut icon" href="favicon2.ico" type="image/x-icon">
        <link rel="icon" href="favicon2.ico" type="image/x-icon">
    </head>

    <body>
        <div id="domov">
                        <a class="domov" href="uvod"> <img src="leo.png" height=80  width=80  > </a>          
        </div>
        <div id="hlavicka">
            <a class="nadpis" href="uvod"> DATALEO</a>          
        </div>
        
        <div id="triOkna">

            <?php foreach ($spravy as $sprava) : ?>
                <p class="sprava"><?= $sprava ?></p>
            <?php endforeach ?>

            <div id="triOkna">

                <?php $this->kontroler->vypisPohlad(); ?>

            </div>
            <div id="pata">
                © DATALEO, Denisa Starinská (2016)
            </div>
        </div>
    </body>

</html>


