<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost"/>
        <meta charset="UTF-8"/>
        <title><?= $titulok ?> </title>
        <meta name="description" content="<?= $popis ?>"/>
        <meta name="keywords" content="<?= $klucove_slova ?>"/>
        <link rel="stylesheet" href="style.css" type="text/css"/>     
        <link rel="shortcut icon" href="favicon.ico"> 
        <link rel="icon" href="favicon.ico"> 
    </head>

    <body>
        <div id="triOkna">
            <div id="hlavicka">
                DATALEO
            </div>

            <?php foreach ($spravy as $sprava) : ?>
                <p class="sprava"><?= $sprava ?></p>
            <?php endforeach ?>

            <div id="triOkna">

                <?php $this->kontroler->vypisPohlad(); ?>

            </div>
            <div id="pata">
                © DATALEO, Denisa Starinská (2016)
            </div>
        </div>
    </body>
    
</html>


