<h1> <?= $zdroje_ukazka['nazov']; ?></h1>

                
               <?= $zdroje_ukazka['druh_zdroja']; ?><br> 
                <?= $zdroje_ukazka['nazov']; ?><br> 
                <?= $zdroje_ukazka['podnazov']; ?><br> 
                <?= $zdroje_ukazka['vydanie']; ?><br> 
                <?= $zdroje_ukazka['miesto_vydania']; ?><br> 
                <?= $zdroje_ukazka['rok_vydania']; ?><br> 
                <?= $zdroje_ukazka['isbn']; ?><br> 
                <?= $zdroje_ukazka['issn']; ?><br> 
                <?= $zdroje_ukazka['doi']; ?><br> 
                <?= $zdroje_ukazka['strany']; ?><br> 
                <?= $zdroje_ukazka['url']; ?><br> 
                <?= $zdroje_ukazka['datum_aktualizacie']; ?><br> 
                <?= $zdroje_ukazka['datum_pridania']; ?><br> 
                <?= $zdroje_ukazka['hodnotenie']; ?><br> 
                <?= $zdroje_ukazka['poznamka']; ?><br> 

           
 