<div id="administracia">

    <a href="administracia"> Vstup do vlastnej knižnice. </a>

</div>

<div id="uvod">

    <h1>Úvodná stránka Datalea</h1> <br>
    <p><b>1. CITOVANIE </b></p>

    <p><b>Bibliografický odkaz </b> – údaj opisujúci prameň alebo jeho časť dostatočne presne a podrobne na jeho identifikáciu a na umožnenie lokalizácie. Odkazy v odborných a vedeckých publikáciách majú spravidla podobu zoznamov použitej literatúry na konci textu, použitej literatúry pod čiarou, menej často aj v texte samotnom.</p><br>

    <p><b>Citácia </b>– uvedenie príslušného odkazu v rámci textu alebo inej formy obsahu. Citácia sa viaže na odkaz, t. j. odkaz obsahuje podrobnejšie údaje o citovanej publikácii. Informácie obsiahnuté v odkaze musia byť dostatočne jasné na identifikáciu citovaného materiálu. Preto spôsob citovania ovplyvňuje aj štýl odkazov, ich umiestnenie, usporiadanie a pod.</p><br>

    <p><b>Údaje pre tvorbu odkazov a citácií by sa mali preberať priamo z publikácie.</b> V prípade tlačených publikácií je to najmä titulný list a tiráž. Titulný list je v knihách spravidla tretia alebo piata strana publikácie, ktorá obsahuje údaje o autorovi, názve, vydavateľovi a pod. Tiráž je najčastejšie posledná potlačená strana knihy. Ak je nevyhnutné uviesť v odkaze údaj, ktorý sa neprebral priamo z publikácie, uvádza sa v hranatých zátvorkách.</p><br>

    <p><b>Bibliografický odkaz </b> – údaj opisujúci prameň alebo jeho časť dostatočne presne a podrobne na jeho identifikáciu a na umožnenie lokalizácie. Odkazy v odborných a vedeckých publikáciách majú spravidla podobu zoznamov použitej literatúry na konci textu, použitej literatúry pod čiarou, menej často aj v texte samotnom.</p><br>

    <p><b>Citácia </b>– uvedenie príslušného odkazu v rámci textu alebo inej formy obsahu. Citácia sa viaže na odkaz, t. j. odkaz obsahuje podrobnejšie údaje o citovanej publikácii. Informácie obsiahnuté v odkaze musia byť dostatočne jasné na identifikáciu citovaného materiálu. Preto spôsob citovania ovplyvňuje aj štýl odkazov, ich umiestnenie, usporiadanie a pod.</p><br>

    <p><b>Údaje pre tvorbu odkazov a citácií by sa mali preberať priamo z publikácie.</b> V prípade tlačených publikácií je to najmä titulný list a tiráž. Titulný list je v knihách spravidla tretia alebo piata strana publikácie, ktorá obsahuje údaje o autorovi, názve, vydavateľovi a pod. Tiráž je najčastejšie posledná potlačená strana knihy. Ak je nevyhnutné uviesť v odkaze údaj, ktorý sa neprebral priamo z publikácie, uvádza sa v hranatých zátvorkách.</p><br>

    <p><b>2. METÓDY CITOVANIA</b></p>

    <p>Norma stanovuje, že údaje v texte (citácie), by mali byť prepojené s bibliografickými údajmi o informačných zdrojoch, ktoré sú podkladom pre dané údaje (odkazy) 
        niektorým z troch nasledujúcich spôsobov: </p>
    <ul>
        <li>Systém mena a dátumu (harvardský systém)</li>
        <li>Číselný systém </li>
        <li>Priebežné poznámky.	</li> </ul>

    <p><b>2. 1 Systém mena a dátumu (harvardský systém)</b></p>
    <p>V starších zdrojoch je uvádzaný aj ako metóda prvého údaja a dátumu. Za citovanou informáciou v texte sa v zátvorke uvedie meno autora a rok. Ak je meno autora 
        súčasťou textu, uvedie sa v zátvorke rok. Ak sa citujú viaceré publikácie toho istého autora s rovnakým rokom, odlíšia sa malými písmenami (a, b, c, atď.) za rokom 
        vo vnútri zátvoriek a tiež za rokom v zozname odkazov (resp. zozname použitej literatúry). Ak sa citujú konkrétne časti publikácie, môže sa za rokom uviesť číslo 
        strany.</p> 
    <p>Pri tejto metóde citovania je nevyhnutné upraviť zoznam odkazov (resp. zoznam použitej literatúry) tak, aby za menom autora (autorov) nasledoval rok vydania. 
    <p>Zoznam sa v tomto prípade usporadúva abecedne podľa priezviska autora.</p>
    <p><b>Táto metóda sa odporúča aj pre citovanie v záverečných prácach.</b></p>

    <p><b>Príklad citovania systémom mena a dátumu</b></p>
    <p>Text:</p>
    <p>Hypotézu potvrdili výsledky výskumov publikovaných Baumgartnerom (1998). Možno ich doložiť aj ďalšími prácami (Benková, 1999a, s. 223; Benková, 1999b, s. 28; 
        Bulla, 2002, s. 102).</p> 

    <p>Použitá literatúra: </p> 
    <p>BAUMGARTNER, Ján a i. 1998. <em>Ochrana a udržiavanie genofondu zvierat, šľachtenie zvierat</em> : výskumná správa. Nitra : VÚŽV. 78 s.</p>
    <p>BENKOVÁ, Janka. 1999a. Analýza mäsovej úžitkovosti sliepok a kohútov génovej rezervy VÚZV-SCHŠH v Ivanke pri Dunaji. In <em>Journal of Farm Animal Science</em>, roč. 32, s. 219-225. ISSN 1335-3961.</p>                            
    <p>BENKOVÁ, Janka a i. 1999b.  <em>Tvorba, uchovanie a využitie biologických vlastností génových rezerv hydiny</em> : výskumná správa. Ivanka pri Dunaji : Stanica chovu a šľachtenia hydiny. 28 s.</p>
    <p>BULLA, Jozef. 2002. Frequencies of the ESR genotypes and alleles in Slovak populations of Large White and White Meaty breeds. In <em>20. Genetické dny</em>. Brno : Mendelova zemědělská a lesnická univerzita, s. 98-103. ISBN 80-7157-607-7. </p> 
    <p>&nbsp;</p> 
    <p><b>2. 2 Číselný systém</b></p>
    Za citovanou informáciou v texte sa uvedie poradové číslo citácie. Rovnaké číslo dostane aj záznam citovanej publikácie v zozname odkazov (resp. zozname použitej literatúry).  Čísla sa môžu uvádzať v okrúhlych zátvorkách, hranatých zátvorkách alebo ako horné indexy. Ak sa citujú konkrétne časti publikácie, môže sa za poradovým číslom uviesť číslo strany. Pri opakovanom citovaní sa použije to číslo, ktoré bolo publikácii pridelené prvý raz.
    Pri tejto metóde sa zoznam použitej literatúry usporiada podľa poradového čísla citácie. 

    <p><b>Príklad citovania číselným systémom</b></p>
    <p>Text:</p>
    <p>Programový balík je dostupný pre Unix/Linux, Windows a Mac na mirroroch (zrkadlených serveroch) CRAN. R-ko má významnú používateľskú komunitu aj na Slovensku a v ČR [25].
        V prvej oblasti majú významné postavenie systémy založené na textovom procesore TEX a jeho nadstavbe LATEX [26, 27].</p>
    <p>Použitá literatúra:</p>
    <p>25. PEKÁR, S. &ndash; BRABEC, M. Moderní analýza biologických dat. 1. díl : zobecněné lineární modely v prostředí R. Praha : Scientia, 2009. 225 s. ISBN 978-80-86960-44-9.</p>
    <p>26. KOPKA, H. &ndash; DALY, P. W. 2004. LATEX : podrobný průvodce. Brno : Computer Press, 2004. 576 s. ISBN 80-7226-973-9. </p>
    <p>27. RYBIČKA, J. LATEX pro začátečníky. Brno : Konvoj, 2003. 238 s. ISBN 80-7302-049-1.</p>

    <p>&nbsp;</p>
    <p><b>2. 3 Priebežné poznámky</b></p>
    <p>Podobne ako v prípade číselného systému sa za citovanou informáciou uvedie poradové číslo citácie (v okrúhlych zátvorkách, hranatých zátvorkách alebo ako 
        horné indexy) avšak bližšie údaje umožňujúce identifikovať položku v zozname odkazov sú v poznámkach (spravidla pod čiarou), spolu s inými poznámkami. Jednotlivé 
        poradové čísla sa potom nevzťahujú len na citácie ale aj na poznámky rôzneho druhu. Každá položka v poznámkach dostáva nové číslo, aj opakovaná citácia toho 
        istého diela. Súčasťou poznámky o citácii je potom aj číslo odkazu (resp. položky v zozname použitej literatúry).</p>
    <p>Ak sa citujú konkrétne časti publikácie, uvádza sa v poznámke aj číslo strany.</p>

    <p><b>Príklad citovania metódou priebežných poznámok</b></p> 
    <p>Text:</p>
    <p>..... dôvody pre citovanie ako splácanie účtu zakladateľom odboru, vyjadrenie vzťahu k príbuzným prácam, uvedenie metodológie, technického vybavenia... 
        8 Naproti tomu,  Meško a i.9uvádzajú, že sa môžeme stretnúť s tým, že za ... Podľa Best Practice Guidelines on Publication Ethics10 .... </p>

    <p>Poznámky:
    <p>8. GARFIELD, odk. 4</p>
    <p>9. MEŠKO, odk. 5, s. 56	</p>
    <p>10. prel. Osvedčené postupy pre publikačnú etiku</p>

    <p>Použitá literatúra: </p>
    <p>4. GARFIELD, Eugene. Can citation indexing be automated? In Statistical Association Methods for Mechanized Documentation : Symposium Proceedings. Washington : 
        National Bureau of Standards Miscellaneous. Publication, č. 269, 1965, s. 189-192. </p>
    <p>5. MEŠKO, Dušan. a i. Akademická príručka. 2. dopln. vyd. Bratislava : Osveta, 2005. 496 s. ISBN 80-8063-200-6.</p>

</div>
