
                <div id="zdroje">
                    <h1>Zoznam zdrojov</h1>
 Zoradit podla:
                <a href="clanek/uvod">Nazov</a>
                <a href="clanek">Autor</a>
                <a href="kontakt">Rok</a>		
                <a href="kontakt">Druh</a>	
<table>
    <?php foreach ($zdroje as $zdroj) : ?>
        <tr>
            <td>
                <?= $zdroj['nazov']; ?> 
                <?= $zdroj['nazov']; ?>
                <?= $zdroj['rok_vydania']; ?>
                <?= $zdroj['datum_pridania']; ?>
                <?= $zdroj['hodnotenie']; ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>

   </div>



<div id="ukazka">
<h1> <?= $zdroje_ukazka['nazov']; ?></h1>


Druh zdroja:  <?php
if (!$zdroje_ukazka['druh_zdroja']) {
    echo "-";
} else {
    echo $zdroje_ukazka['druh_zdroja'];
}
?><br> 

Nazov:  <?php
if (!$zdroje_ukazka['nazov']) {
    echo "-";
} else {
    echo $zdroje_ukazka['nazov'];
}
?><br>

Podnazov:  <?php
if (!$zdroje_ukazka['podnazov']) {
    echo "-";
} else {
    echo $zdroje_ukazka['podnazov'];
}
?><br>

Vydanie:  <?php
if (!$zdroje_ukazka['vydanie']) {
    echo "-";
} else {
    echo $zdroje_ukazka['vydanie'];
}
?><br>

Miesto vydania:  <?php
if (!$zdroje_ukazka['miesto_vydania']) {
    echo "-";
} else {
    echo $zdroje_ukazka['miesto_vydania'];
}
?><br>

Rok vydania:  <?php
if (!$zdroje_ukazka['rok_vydania']) {
    echo "-";
} else
    echo $zdroje_ukazka['rok_vydania'];
?><br>

ISSN:  <?php
if (!$zdroje_ukazka['isbn']) {
    echo "-";
} else {
    echo $zdroje_ukazka['isbn'];
}
?><br>

ISSN:  <?php
if (!$zdroje_ukazka['issn']) {
    echo "-";
} else {
    echo $zdroje_ukazka['issn'];
}
?><br>

DOI:  <?php
if (!$zdroje_ukazka['doi']) {
    echo "-";
} else {
    echo $zdroje_ukazka['doi'];
}
?><br>

Počet strán:  <?php
if (!$zdroje_ukazka['strany']) {
    echo "-";
} else {
    echo $zdroje_ukazka['strany'];
}
?><br>

URL adresa:  <?php
if (!$zdroje_ukazka['url']) {
    echo "-";
} else {
    echo $zdroje_ukazka['url'];
}
?><br>

Dátum aktualizácie: <?php
if (!$zdroje_ukazka['datum_aktualizacie']) {
    echo "-";
} else {
    echo $zdroje_ukazka['datum_aktualizacie'];
}
?><br> 

Dátum pridania: <?php
if (!$zdroje_ukazka['datum_pridania']) {
    echo "-";
} else {
    echo $zdroje_ukazka['datum_pridania'];
}
?><br>

Vlastné hodnotenie:  <?php
if (!$zdroje_ukazka['hodnotenie']) {
    echo "-";
} else {
    echo $zdroje_ukazka['hodnotenie'];
}
?><br>

Poznámka:  <?php
if (!$zdroje_ukazka['poznamka']) {
    echo "-";
} else {
    echo $zdroje_ukazka['poznamka'];
}
?><br>




                </div>