<h1>Zoznam zdrojov</h1>
 Zoradit podla:
                <a href="clanek/uvod">Nazov</a>
                <a href="clanek">Autor</a>
                <a href="kontakt">Rok</a>		
                <a href="kontakt">Druh</a>	
<table>
    <?php foreach ($zdroje as $zdroj) : ?>
        <tr>
            <td>
                <?= $zdroj['nazov']; ?> 
                <?= $zdroj['nazov']; ?>
                <?= $zdroj['rok_vydania']; ?>
                <?= $zdroj['datum_pridania']; ?>
                <?= $zdroj['hodnotenie']; ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>

