<head>
    <script type="text/javascript">/*
     Copy text from any appropriate field to the clipboard
     By Craig Buckler, @craigbuckler
     use it, abuse it, do whatever you like with it!
     */
        (function () {

            'use strict';

            // click events
            document.body.addEventListener('click', copy, true);

            // event handler
            function copy(e) {

                // find target element
                var
                        t = e.target,
                        c = t.dataset.copytarget,
                        inp = (c ? document.querySelector(c) : null);

                // is element selectable?
                if (inp && inp.select) {

                    // select text
                    inp.select();

                    try {
                        // copy text
                        document.execCommand('copy');
                        inp.blur();

                        // copied animation
                        t.classList.add('copied');
                        setTimeout(function () {
                            t.classList.remove('copied');
                        }, 1500);
                    }
                    catch (err) {
                        alert('please press Ctrl/Cmd+C to copy');
                    }

                }

            }

        })();
    </script>
</head>

<div id="administracia" >
    <img src="resources/ikony/user.png"> <?php echo $pouzivatel['meno'] ?> 
    <a  class= "tucny_odkaz" href="uvod/odhlasit"> <img src="resources/ikony/exit.png"> </a>
</div>


<div id="navigacia">
    <a class="tucny_odkaz" href="uvod"> DATALEO </a>  >> <a class="tucny_odkaz" href="zdroje">Moja knižnica </a>>> <?= $zdroje_ukazka['nazov']; ?>
</div>

<?php $cesta_k_suboru = 'uploads/' . $zdroje_ukazka['zdroj_id'] . '.pdf'; ?>




<div id="ukazkaZdroja">



   


    <table class="ukazka" border="0">

        <tr class="ukazka">
            <td class="tucne">Názov: </td> <?php
            if (!$zdroje_ukazka['nazov']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['nazov'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr class="ukazka">
            <td class="tucne">Podnázov: </td> <?php
            if (!$zdroje_ukazka['podnazov']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['podnazov'];
                echo "</td>";
            }
            ?>
        </tr>

        
         <tr class="ukazka">
            <td class="tucne">Názov príspevku: </td> <?php
            if (!$zdroje_ukazka['prispevok']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['prispevok'];
                echo "</td>";
            }
            ?>
        </tr>
        
         <tr class="ukazka">
            <td class="tucne">Zodpovednosť za zdrojový dokument: </td> <?php
            if (!$zdroje_ukazka['zodpovednost']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['zodpovednost'];
                echo "</td>";
            }
            ?>
        </tr>
        
        
        <tr class="ukazka">
            <td class="tucne">Druh zdroja: </td> <?php
            if (!$zdroje_ukazka['druh_zdroja']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                if ($zdroje_ukazka['druh_zdroja'] == 'kniha')
                    echo 'Kniha';
                if ($zdroje_ukazka['druh_zdroja'] == 'cast_knihy')
                    echo 'Časť knihy';
                if ($zdroje_ukazka['druh_zdroja'] == 'clanok')
                    echo 'Článok';
                if ($zdroje_ukazka['druh_zdroja'] == 'zbornik')
                    echo 'Zborník';
                if ($zdroje_ukazka['druh_zdroja'] == 'prispevok_v_zborniku')
                    echo 'Príspevok v zborníku';
                if ($zdroje_ukazka['druh_zdroja'] == 'akademicka_praca')
                    echo 'Akademická práca';
                if ($zdroje_ukazka['druh_zdroja'] == 'elektronicka_kniha')
                    echo 'Elektronická kniha';
                if ($zdroje_ukazka['druh_zdroja'] == 'cast_elektronickej_knihy')
                    echo 'Časť elektronickej knihy';
                if ($zdroje_ukazka['druh_zdroja'] == 'elektronicky_clanok')
                    echo 'Elektronický článok';
                if ($zdroje_ukazka['druh_zdroja'] == 'elektronicky_zbornik')
                    echo 'Elektronický zborník';
                if ($zdroje_ukazka['druh_zdroja'] == 'elektronicka_akademicka_praca')
                    echo 'Elektronická akademická práca';
                if ($zdroje_ukazka['druh_zdroja'] == 'elektronicky_prispevok_v_zborniku')
                    echo 'Elektronický príspevok v zborníku';
                if ($zdroje_ukazka['druh_zdroja'] == 'web')
                    echo 'Web';
                if ($zdroje_ukazka['druh_zdroja'] == 'webova_stranka')
                    echo 'Webová stránka';
                if ($zdroje_ukazka['druh_zdroja'] == 'prispevok_na_webe')
                    echo 'Príspevok na webe';
                if ($zdroje_ukazka['druh_zdroja'] == 'iny_dokument')
                    echo 'Iný dokument';
                if ($zdroje_ukazka['druh_zdroja'] == 'nepublikovany_dokument')
                    echo 'Nepublikovaný dokument';
                echo "</td>";
            }
            ?>
        </tr>

        <tr class="ukazka">
            <td class="tucne">Autor/i: </td> <?php
            if (!$autori) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
            }
            foreach ($autori as $autor):
                ?>
                <?= $autor['titul_pred'] . " " . $autor['meno'] . " " . $autor['priezvisko'] . " " . $autor['titul_po'] . "<br>"; ?>
            <?php endforeach ?>
        </tr>

        <tr class="ukazka">
            <td class="tucne">Okruh/y: </td> <?php
            if (!$okruhy) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
            }
            foreach ($okruhy as $okruh):
                ?>
                <?= $okruh['nazov_okruhu']; ?>
            <?php endforeach ?>
        </tr>

        <tr class="ukazka">
            <td class="tucne">Kľúčové slová: </td> <?php
            if (!$slovicka) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
            }
            foreach ($slovicka as $slovicko):
                ?>
                <?= $slovicko['klucove_slovo']; ?>
            <?php endforeach ?>
        </tr>

        <tr class="ukazka">
            <td class="tucne">Vydanie /verzia: </td> <?php
            if (!$zdroje_ukazka['vydanie']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['vydanie'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr class="ukazka">
            <td class="tucne">Miesto vydania: </td> <?php
            if (!$zdroje_ukazka['miesto_vydania']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['miesto_vydania'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Vydavateľstvo: </td> <?php
            if (!$zdroje_ukazka['vydavatelstvo']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['vydavatelstvo'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Rok vydania: </td> <?php
            if (!$zdroje_ukazka['rok_vydania']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['rok_vydania'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">ISBN: </td> <?php
            if (!$zdroje_ukazka['isbn']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['isbn'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">ISSN: </td> <?php
            if (!$zdroje_ukazka['issn']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['issn'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">DOI: </td> <?php
            if (!$zdroje_ukazka['doi']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['doi'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Počet strán: </td> <?php
            if (!$zdroje_ukazka['strany']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['strany'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Rozsah:  </td> <?php
            if ((!$zdroje_ukazka['od'])||(!$zdroje_ukazka['do'])) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['od'].'-'.$zdroje_ukazka['do'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">URL adresa: </td> <?php
            if (!$zdroje_ukazka['url']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['url'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Dátum vydania: </td> <?php
            if (!$zdroje_ukazka['datum_vydania']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['datum_vydania'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Dátum aktualizácie: </td> <?php
            if (!$zdroje_ukazka['datum_aktualizacie']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['datum_aktualizacie'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Dátum pridania: </td> <?php
            if (!$zdroje_ukazka['datum_pridania']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['datum_pridania'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Druh nosiča: </td> <?php
            if (!$zdroje_ukazka['nosic']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['nosic'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Hodnotenie: </td> <?php
            if (!$zdroje_ukazka['hodnotenie']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['hodnotenie'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr class="ukazka">
            <td class="tucne">Poznamka: </td> <?php
    if (!$zdroje_ukazka['poznamka']) {
        echo "<td>-</td>";
    } else {
        echo "<td>";
        echo $zdroje_ukazka['poznamka'];
        echo "</td>";
    }
            ?>
        </tr>


    </table>
    
    
   

    
    
    <a class="potvrdzovacie_tlacidlo" href="http://localhost/editor/<?= $_GET['zdroj_id'] ?>"> Editovať</a>
    <a class="potvrdzovacie_tlacidlo" href="http://localhost/editor/<?= $_GET['zdroj_id'] ?>/odstranit"> Vymazať </a>

    <?php if (file_exists($cesta_k_suboru)): ?>
        <a class="potvrdzovacie_tlacidlo" href="http://localhost/<?= $cesta_k_suboru ?>"> Stiahnuť </a>
    <?php endif ?>
        
        
        
        
          <?php if (($zdroje_ukazka['druh_zdroja'] != 'web') && ($zdroje_ukazka['druh_zdroja'] != 'webova_stranka')
            && ($zdroje_ukazka['druh_zdroja'] != 'iny_dokument') && ($zdroje_ukazka['druh_zdroja'] != 'nepublikovany_dokument')): ?>
        <br><br><b>Citácia:</b> <?= $zdroje_ukazka['citacia'] ?>
    <br><br>
    

    <input type="text" id="website" class="website" value="<?= $zdroje_ukazka['citacia'] ?>" />
    <button id="website" class="website" data-copytarget="#website">copy</button> 
   <br>Tlačidlom premiestnite obsah citácie do schránky, 
    následne ju pomocou CTRL + V môžete vložiť do textového dokumentu.
    
    <?php endif ?>
</div>




<div id="pdf">

<?php if (file_exists($cesta_k_suboru)): ?>
        <object  data=<?= $cesta_k_suboru ?> width="650" height="800" >
            <p>Tento webový prehliadač nepodporuje PDF plugin.  <a href="http://localhost/<?= $cesta_k_suboru ?>">Kliknite sem pre externé zobrazenie.</a>
        </object>


<?php elseif ($zdroje_ukazka['url']): ?>
        <object  data="<?= $zdroje_ukazka['url'] ?>" width="650" height="800" >

            <p>Problém s načítaním ukážky zdroja. Skontrolujte, či ste zdroj pridali.</a></p>
        </object>

<?php else: ?>
        Ukážka zdroja neexistuje.
<?php endif; ?>
        
        
        
        

</div>




