

<div id="administracia" >
    <img src="resources/ikony/user.png"> <?php echo $pouzivatel['meno'] ?> 
    <a  class= "tucny_odkaz" href="uvod/odhlasit"> <img src="resources/ikony/exit.png"> </a>
</div>


<div id="navigacia">
    <a class="tucny_odkaz" href="uvod"> DATALEO </a>  >> <a class="tucny_odkaz" href="zdroje">Moja knižnica </a>>> <?= $zdroje_ukazka['nazov']; ?>
</div>

<div id="pdf">
    <?php $cesta_k_suboru = 'uploads/' . $zdroje_ukazka['zdroj_id'] . '.pdf'; ?>
    <?php if (file_exists($cesta_k_suboru)): ?>
        <object  data=<?= $cesta_k_suboru ?> width="650" height="800" >
            <p>Tento webový prehliadač nepodporuje PDF plugin.  <a href="http://localhost/<?= $cesta_k_suboru ?>">Kliknite sem pre externé zobrazenie.</a>
        </object>


    <?php elseif ($zdroje_ukazka['url']): ?>
        <object  data="<?= $zdroje_ukazka['url'] ?>" width="650" height="800" >

            <p>Problém s načítaním ukážky zdroja. Skontrolujte, či ste zdroj pridali.</a></p>
        </object>

    <?php else: ?>
        Ukážka zdroja neexistuje.
    <?php endif; ?>

</div>




<div id="ukazkaZdroja">
    <table  border="0">


        <tr>
            <td>Autor/i: </td> <?php
            if (!$autori) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
            }
            foreach ($autori as $autor):
                ?>
                <?= $autor['titul_pred'] . " " . $autor['meno'] . " " . $autor['priezvisko'] . " " . $autor['titul_po'] . "<br>"; ?>
            <?php endforeach ?>
        </tr>

        <tr>
            <td>Okruh/y: </td> <?php
            if (!$okruhy) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
            }
            foreach ($okruhy as $okruh):
                ?>
                <?= $okruh['nazov_okruhu']; ?>
            <?php endforeach ?>
        </tr>

        <tr>
            <td>Zdroj ID: </td> <?php
            if (!$zdroje_ukazka['zdroj_id']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['zdroj_id'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr>
            <td> Pouzivatel ID: </td> <?php
            if (!$zdroje_ukazka['pouzivatel_id']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['pouzivatel_id'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr>
            <td> Druh zdroja: </td> <?php
            if (!$zdroje_ukazka['druh_zdroja']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['druh_zdroja'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr>
            <td>Nazov: </td> <?php
            if (!$zdroje_ukazka['nazov']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['nazov'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr>
            <td>Podnazov: </td> <?php
            if (!$zdroje_ukazka['podnazov']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['podnazov'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr>
            <td>Vydanie: </td> <?php
            if (!$zdroje_ukazka['vydanie']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['vydanie'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr>
            <td>Miesto vydania: </td> <?php
            if (!$zdroje_ukazka['miesto_vydania']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['miesto_vydania'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>Nakladatelstvo: </td> <?php
            if (!$zdroje_ukazka['vydavatelstvo']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['vydavatelstvo'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>Rok_vydania: </td> <?php
            if (!$zdroje_ukazka['rok_vydania']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['rok_vydania'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>ISBN: </td> <?php
            if (!$zdroje_ukazka['isbn']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['isbn'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>ISSN: </td> <?php
            if (!$zdroje_ukazka['issn']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['issn'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>DOI: </td> <?php
            if (!$zdroje_ukazka['doi']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['doi'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>Pocet stran: </td> <?php
            if (!$zdroje_ukazka['strany']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['strany'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>URL adresa: </td> <?php
            if (!$zdroje_ukazka['url']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['url'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>Datum aktualizacie: </td> <?php
            if (!$zdroje_ukazka['datum_aktualizacie']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['datum_aktualizacie'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>Datum pridania: </td> <?php
            if (!$zdroje_ukazka['datum_pridania']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['datum_pridania'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>Hodnotenie: </td> <?php
            if (!$zdroje_ukazka['hodnotenie']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['hodnotenie'];
                echo "</td>";
            }
            ?>
        </tr>
        <tr>
            <td>Poznamka: </td> <?php
            if (!$zdroje_ukazka['poznamka']) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
                echo $zdroje_ukazka['poznamka'];
                echo "</td>";
            }
            ?>
        </tr>

        <tr>
            <td>Klucove slova: </td> <?php
            if (!$slovicka) {
                echo "<td>-</td>";
            } else {
                echo "<td>";
            }
            foreach ($slovicka as $slovicko):
                ?>
                <?= $slovicko['klucove_slovo']; ?>
            <?php endforeach ?>
        </tr>



    </table>
    <a class="potvrdzovacie_tlacidlo" href="http://localhost/editor/<?= $_GET['zdroj_id'] ?>"> Editovať</a>
    <a class="potvrdzovacie_tlacidlo" href="http://localhost/editor/<?= $_GET['zdroj_id'] ?>/odstranit"> Vymazať </a>
    
    <?php if (file_exists($cesta_k_suboru)): ?>
        <a class="potvrdzovacie_tlacidlo" href="http://localhost/<?= $cesta_k_suboru ?>"> Stiahnuť </a>
    <?php endif ?>
</div>




